import{a as f,S as b,i as n}from"./assets/vendor-CNqCr-V-.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function t(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(o){if(o.ep)return;o.ep=!0;const s=t(o);fetch(o.href,s)}})();f.defaults.baseURL="https://pixabay.com/api/";const w="53588295-343522c470cf6eee7e060c944",m=15;async function S(r,e){return(await f.get("",{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:m}})).data}const p=document.querySelector(".gallery"),y=document.querySelector(".load-more"),h=document.querySelector(".loader"),v=new b(".gallery a",{captionsData:"alt",captionDelay:250});function q(r){const e=r.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${t.likes}</p>
          <p><b>Views</b> ${t.views}</p>
          <p><b>Comments</b> ${t.comments}</p>
          <p><b>Downloads</b> ${t.downloads}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",e),v.refresh()}function E(){p.innerHTML=""}function P(){h.classList.remove("hidden")}function $(){h.classList.add("hidden")}function R(){y.classList.remove("hidden")}function l(){y.classList.add("hidden")}const M=document.querySelector(".form"),B=document.querySelector(".load-more"),H=document.querySelector(".gallery");let g="",a=1,c=0,u=0;M.addEventListener("submit",I);B.addEventListener("click",O);async function I(r){r.preventDefault();const e=r.currentTarget.elements.searchQuery.value.trim();if(!e){n.error({message:"Please enter a search query!",position:"topRight"});return}g=e,a=1,c=0,u=0,E(),l(),await L()}async function O(){a+=1,await L(!0)}async function L(r=!1){try{P();const e=await S(g,a),{hits:t,totalHits:i}=e;if(a===1&&t.length===0){l(),n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}a===1&&(c=i,n.success({message:`Hooray! We found ${c} images.`,position:"topRight"})),q(t),u+=t.length,u<c&&t.length===m?R():(l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"})),r&&A()}catch{l(),n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{$()}}function A(){const r=H.querySelector(".gallery-item");if(!r)return;const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
